# Generated by Django 2.1.2 on 2018-11-05 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='string', max_length=150)),
                ('category', models.CharField(choices=[('Objects', 'Objects'), ('Animals', 'Animals'), ('Abstract', 'Abstract'), ('Festivals', 'Festivals'), ('Food', 'Food'), ('Lifestyle', 'Lifestyle'), ('Nature', 'Nature'), ('People', 'People')], default='string', max_length=150)),
                ('image', models.ImageField(default='', upload_to='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('rating', models.IntegerField()),
                ('total_image_downloads', models.IntegerField()),
            ],
        ),
    ]
