# Generated by Django 2.1.2 on 2018-11-05 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0004_auto_20181105_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='rating',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='document',
            name='total_image_downloads',
            field=models.IntegerField(default='0'),
        ),
    ]
