# Generated by Django 2.1.2 on 2018-11-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0006_auto_20181105_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('Objects', 'Objects'), ('Animals', 'Animals'), ('Abstract', 'Abstract'), ('Festivals', 'Festivals'), ('Food', 'Food'), ('Lifestyle', 'Lifestyle'), ('Nature', 'Nature'), ('People', 'People')], default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(default='', max_length=150),
        ),
    ]
