# Generated by Django 2.1.2 on 2018-11-15 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0007_auto_20181114_2056'),
        ('finalapp', '0007_auto_20181110_1908'),
    ]

    operations = [
    ]
