# Generated by Django 2.1.2 on 2018-11-16 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0008_merge_20181115_2315'),
        ('finalapp', '0008_merge_20181115_2225'),
    ]

    operations = [
    ]
