# Generated by Django 2.1.2 on 2018-11-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0010_auto_20181118_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('Objects', 'Objects'), ('Animals', 'Animals'), ('Abstract', 'Abstract'), ('Festivals', 'Festivals'), ('Food', 'Food'), ('Lifestyle', 'Lifestyle'), ('Nature', 'Nature'), ('People', 'People'), ('Architecture', 'Architecture'), ('Sports', 'Sports'), ('Fashion', 'Fashion')], default='', max_length=150),
        ),
    ]
