# Generated by Django 2.1.2 on 2018-12-13 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0014_auto_20181213_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='document',
            name='total_image_downloads',
        ),
    ]
